runtime: nodejs20
service: default

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*)
  static_files: \1
  upload: (.*)
  secure: always

env_variables:
  NODE_ENV: 'production'
